# Generated by Django 5.2 on 2025-05-27 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userchallenge_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='started_at',
            field=models.DateField(default=datetime.datetime(2025, 5, 27, 14, 43, 29, 642763), null=True),
        ),
    ]
