# Generated by Django 5.2 on 2025-05-30 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userchallenge_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='started_at',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 16, 17, 33, 79127), null=True),
        ),
    ]
