# Generated by Django 5.0.1 on 2025-05-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created_at',
        ),
    ]
