# Generated by Django 5.2 on 2025-05-30 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userchallenge_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='started_at',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 19, 43, 4, 663444), null=True),
        ),
    ]
