<<<<<<< HEAD
# Generated by Django 5.2 on 2025-07-21 19:04

=======
# Generated by Django 5.0.1 on 2025-06-09 14:46

import datetime
>>>>>>> 613dd7b7dcb12e9e4fe223dec507d4e9e5f256fc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_userchallenge_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='started_at',
<<<<<<< HEAD
            field=models.DateField(blank=True, null=True),
=======
            field=models.DateField(default=datetime.datetime(2025, 6, 9, 17, 46, 20, 977322), null=True),
>>>>>>> 613dd7b7dcb12e9e4fe223dec507d4e9e5f256fc
        ),
    ]
