# Generated by Django 5.0.1 on 2025-06-09 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userchallenge_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='started_at',
            field=models.DateField(default=datetime.datetime(2025, 6, 9, 18, 30, 1, 52561), null=True),
        ),
    ]
