# Generated by Django 5.0.1 on 2025-06-28 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_userchallenge_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='started_at',
            field=models.DateField(default=datetime.datetime(2025, 6, 28, 12, 49, 52, 652301), null=True),
        ),
    ]
