# Generated by Django 5.0.1 on 2025-05-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('repetitions', models.PositiveIntegerField(blank=True, help_text='Number of repetitions (optional)', null=True)),
                ('calories_burned', models.PositiveIntegerField(help_text='Estimated calories burned per session')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('balance', 'Balance')], max_length=50)),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.musclegroup')),
            ],
        ),
    ]
