# Generated by Django 5.0.1 on 2025-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminforweb', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group',
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(blank=True, to='userprofile.musclegroup'),
        ),
    ]
