# Generated by Django 5.0.1 on 2025-05-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminforweb', '0002_remove_exercise_muscle_group_exercise_muscle_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=25, null=True),
        ),
    ]
