# Generated by Django 5.2 on 2025-05-21 19:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_weeks', models.PositiveIntegerField()),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('day_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(28)])),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('repetitions', models.PositiveIntegerField(blank=True, help_text='Number of repetitions (optional)', null=True)),
                ('calories_burned', models.PositiveIntegerField(help_text='Estimated calories burned per session')),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=25, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('stretching', 'Stretching'), ('warming up', 'Warming up')], max_length=50)),
                ('muscle_group', models.ManyToManyField(blank=True, to='userprofile.musclegroup')),
            ],
        ),
        migrations.CreateModel(
            name='DayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('challenge_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.challengeday')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
            ],
        ),
    ]
