# Generated by Django 5.2 on 2025-05-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='goal',
            field=models.CharField(blank=True, choices=[('hypertrophy', 'Hypertrophy'), ('muscle_definition', 'Muscle Definition'), ('lose_weight', 'Lose Weight')], max_length=20, null=True),
        ),
    ]
