# Generated by Django 5.2 on 2025-05-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='calories_burned',
            new_name='base_calories_burned',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='repetitions',
            new_name='base_duration_seconds',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='duration_seconds',
            new_name='base_repetitions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='level',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises_gif/'),
        ),
    ]
