# Generated by Django 5.2 on 2025-05-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_rename_calories_burned_exercise_base_calories_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayexercise',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='repetitions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dayexercise',
            unique_together={('challenge_day', 'order')},
        ),
    ]
