# Generated by Django 5.2 on 2025-07-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_dayexercise_calories_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeday',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
