# Generated by Django 5.0.1 on 2025-06-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_dayexercise_calories_burned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/')),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
