# Generated by Django 5.0.1 on 2025-06-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_healtharticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='healtharticle',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
