# Generated by Django 5.2.4 on 2025-07-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_challengeday_is_available'),
        ('exercise', '0006_healtharticle_is_visible'),
    ]

    operations = [
    ]
