# Generated by Django 5.2 on 2025-05-21 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('arms', 'Arms'), ('legs', 'Legs'), ('back', 'Back'), ('chest', 'Chest'), ('glutes', 'Glutes'), ('full_body', 'Full Body')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('weight_goal', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, choices=[('hypertrophy', 'Hypertrophy'), ('muscle_definition', 'Muscle Definition'), ('lose_weight', 'Lose Weight')], max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('workout_days', models.JSONField(default=list, help_text="List of days like ['Monday', 'Wednesday']")),
                ('workout_time_per_day', models.TimeField(blank=True, null=True)),
                ('focused_muscle_groups', models.ManyToManyField(blank=True, to='userprofile.musclegroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
